# Use the official Node.js image as the base image
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application source code to the container
COPY . .

# Expose the port that the application will run on
EXPOSE 5000

# Define the command to run your application
CMD ["node", "index.js"]
